language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/basic-printer/basic-printer.ino

install:
    - pip install -U platformio

script:
    - platformio ci --board=d1_mini --board=lolin32 --lib="./src"
